[package]
name = "acme-client"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
openssl = "0.10.71"
hex = "0.4.3"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"